export const ADD_EVENT = 'ADD_EVENT';
export const REMOVE_EVENT = 'REMOVE_EVENT';
export const INIT_EVENT = 'INIT_EVENT';
export const SET_CALENDAR = 'SET_CALENDAR';

export const SET_RECURRING = 'SET_RECURRING';
export const ADD_RECURRING = 'ADD_RECURRING';
export const REMOVE_RECURRING = 'REMOVE_RECURRING';
export const RECURRING_FETCHED = 'RECURRING_FETCHED';