export const ADD_EVENT = 'ADD_EVENT';
export const REMOVE_EVENT = 'REMOVE_EVENT';
export const INIT_EVENT = 'INIT_EVENT';
export const SET_CALENDAR = 'SET_CALENDAR';

export const SET_RECURRING = 'SET_RECURRING';
export const ADD_RECURRING = 'ADD_RECURRING';
export const REMOVE_RECURRING = 'REMOVE_RECURRING';
export const RECURRING_FETCHED = 'RECURRING_FETCHED';

export const ADD_RESOURCE_EVENT = 'ADD_RESOURCE_EVENT';
export const REMOVE_RESOURCE_EVENT = 'REMOVE_RESOURCE_EVENT';
export const SET_RESOURCE_CALENDAR = 'SET_RESOURCE_CALENDAR';

export const UPDATE_RESOURCES = 'UPDATE_RESOURCES';
export const SET_RESOURCES = 'SET_RESOURCES';

export const INIT_BLOG = 'INIT_BLOG';
export const ADD_BLOG = 'ADD_BLOG';
export const UPDATE_BLOG = 'UPDATE_BLOG';
export const REMOVE_BLOG = 'REMOVE_BLOG';
export const GET_BLOG = 'GET_BLOG';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER';
export const GET_USERS = 'GET_USERS';

export const FOUND_USER = 'FOUND_USER';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const CHECKED_IN = 'CHECKED_IN';
export const CHECKED_OUT = 'CHECKED_OUT';
export const DATA_LOADED_FOR_CSV = 'DATA_LOADED_FOR_CSV';
export const UNLOAD_CSV = 'UNLOAD_CSV';
export const CSV_DATA_DELETED = 'CSV_DATA_DELETED';
export const K12GROUP_CHECKED_IN = 'K12GROUP_CHECKED_IN';